

Nombres = [
    "Julio Quevedo",
"Luis Alejandro L",
"Ariel Esdras Pablo Gómez",
"Marco Molina",
"Jerson Cabrera",
"David Enrique Tejada Merlos",
"Luis Karlo Valle Licona",
"Lastenia Diaz ",
"Adriana Marcela Ariza Pertuz",
"Alvaro Sesin",
"Hamed Peñalba ",
"Kelly Marchán",
"Jorge Saldaña ",
"Gustavo Lopez",
"Luis Hernandez",
"Aline Flores ",
"Hernan Castillo",
"Denis Nuñez ",
"Nicolas Chahin",
"Marlon Vega",
"Eduardo Garcia",
"Junny Hernández",
"Danny Yohoros",
"Jose Alberto Acrich Dutar",
"Ramon Sulvaran",
"Isaac Willems Arauz Sanjur ",
"Aquilino Rodriguez",
"Jose Maroto",
"Grettel Alvarado S",
"Félix Alonso Carvajal Elizondo ",
"Karla Aguirre",
"Rodolfo Arguedas",
"Rafael Montero",
"Jonatan Chinchilla Arias ",
"William Rodriguez Chanto",
"Carlos C",
"Jarvick Castillo Castillo ",
"Elvis Illescas Naranjo ",
"Edwin Nahun Barrientos Reyes",
"Aarón Pérez Murillo ",
"Jeffrey Herrera Córdoba",
"Anyelí Ávila Lobo ",
"Philippe Aronson",
"Jorge Pablo Salas Morera",
"Roy Rojas",
"Merlin Montero",
"Steve Vado Rodriguez",
"Daniel Badilla",
"Daniel Hernández Ríos ",
"Jose Jorge Sierra ",
"Cristian Martínez",
"Luis Prieto",
"Luis Rubén Zuchini Cifuentes ",
"Christian Fernando Cabrera Perez",
"Josue Antonio Cardona Samayoa",
"Pedro Brolo Vila",
"Vitelio Donato Rivas",
"Carlos Morales Monterroso",
"Cesar Lara",
"Karen Mendoza De Santos",
"Daniel Luna",
"Yanina Reyes",
"Ariana Moncada",
"Francis Lizeth Martinez Oliva ",
"Javier Prado",
"Abner Morales",
"Erick Lemus ",
"Enrique Valdez Porta ",
"Hernan Alejandro Carrion",
"Sergio Canahuati Romero ",
"Jorge David Paz Giron",
"Alvaro Roberto Torres Salazar",
"Wilhem Gonzalez",
"Angel Maltez",
"Juan Arturo Gramajo Ochoa",
"Wendy Martínez Marquez",
"Oscar Tavico",
"J. Ernesto Santos Cañadas",
"Tulio Josue Doblado Reyes",
"Sergio Garcia",
"Juan Esteban Conde",
"Jose Roberto Aguirre",
"Raúl Hernández Reyna",
"Jorge Solis",
"Ricardo Alfonso Escobedo Dacaret",
"Michell Ayme Velasquez Garcia",
"Carlos Barillas",
"Juan Carlos López Villatoro ",
"Ervin Higueros",
"Ismael Paz",
"Roberto Way",
"Hector Adolfo Alvarado Villatoro",
"Sergio Argueta",
"Manuel Antonio Siekavizza",
"Alan Marroquin",
"Victor Chacon",
"Amilcar Recinos  ",
"Jorge Chang",
"José Victor Lacan Pineda",
"Francisco Maximilian Estrada",
"Andrea Silva",
"Carlos Guzman",
"Oscar Marquez",
"André Reyes",
"Juan Pablo Minondo",
"Jenniffer Ramírez",
"Oscar Mejia Taracena",
"Francisco Jacob ",
"Guillermo A. Gonzalez O.",
"Daniela Corella ",
"Siego Vadillo",
"Julio Gonzalez",
"Alejandro Dubón Ruíz",
"Seily Martinez",
"Hector Canizales",
"Jacobo Kattan",
"Carlo Martinez",
"Milton A. Sican Samayoa  ",
"Carlos Avila Marroquin",
"Oscar/Pharma Mejia",
"Erick Sazo",
"Jens Stubbe",
"Jose Garrido Alvarez",
"Gerardo Ramirez",
"Vania Montecinos",
"Ruben Berrios",
"Josué Alemán",
"Enrique Facusse",
"Alvar Xavier Maldonado Villafranca",
"Enrique Andrade",
"Gabriel Quinonez",
"Gustavo Garcia",
"Ramon Maradiaga",
"Raul Blanco ",
"Roberto Chehade L.",
"Cesar Deras",
"Gerardo Calvo Martínez",
"Gonzalo Aliñado Sosa",
"Luis Fernando Hernández C",
"Mariaceleste Lima",
"Estuardo González Aldan",
"Carlos Silvestre",
"Pedro Luis Lopez Medina",
"Jorge Garmendia ",
"Francisco Tosi",
"Ada Marlen Ramirez Zepeda",
"Luis Echenique",
"Oscar Argueta",
"Carlos Santos ",
"Kathya Pastor ",
"Eduardo Font",
"Herberth Carrillo ",
"Sergio Licardie ",
"Juan Solares",
"José Solares ",
"Jose Antonio Lizarralde",
"Javier Echeverria",
"Jorge Lima",
"Gerardo J. Guillén ",
"Ricardo Sierra",
"Armando Muñoz Sulecio",
"Jorge Matheu ",
"Erick Garcia",
"Jessica Durdaneth Solis Galindo ",
"Aldo Martínez Ferro",
"Vladimiro Rivera ",
"Modesto Cruz",
"Andrés Vila",
"José Méndez ",
"Gustavo Palma",
"Leonard Perez",
"Rodolfo Heinemann",
"Lucrecia Anleu",
"David Maldonado",
"Hernan Franco Mejía",
"Patricia Giacoman",
"Jimy Xavier Vargas Ramirez",
"Ronaldo Gabriel ",
"Orlando Mendez",
"Arturo Blumen",
"Paola Avilez",
"Alejandro Galindo",
"Jose Acajabon",
"Luis Alfredo Rivas ",
"Marvin Veliz ",
"Alberto Cohen",
"Carlos Agustin Galindo Rodas",
"Carlos Morán",
"Yesica Belen Castillo de Rojas",
"Mario Adolfo Erales Villanuev",
"Ricardo Chinchilla",
"Daniel Navarrete",
"Jorge Colindres",
"Judith De Leon ",
"Rene Garcia",
"Maynor Barrera",
"Julián Zaldaña ",
"Otto Morales",
"José L Agüero-Urruela ",
"Mario Arturo Rojas Simon ",
"Pedro Antonio Reyes Dubon ",
"John Franks ",
"Angelo Casco Bruni",
"Gustavo Lopez",
"Diana Lorena Lopez Reyes ",
"Gerardo Baltodano",
"Jose Guillermo Obando Suarez",
"Walter Rodríguez",
"David Girón Monzón",
"Ricardo Orellana ",
"Oscar Paiz",
"Peter Lammens",
"Fernando A.",
"Delmis Lorenzo ",
"Eddy Romero",
"Axel André González Rodríguez",
"Abraham Garcia",
"Ricardo Santos",
"Miguel Florián Gutiérrez",
"Tom Rybar",
"Cristian Rodriguez",
"Alejandro Aguilar",
"Edy Canel",
"Hugo Mendoza",
"Alejandro Escoto",
"Stephan Nathusius ",
"Rolando Bonilla",
"David Cahen",
"Beatriz Chavez  ",
"Gabriel Rodriguez",
"Wendy Débora Sosa",
"Juan Francisco Yanes",
"Sergio Canahuati Romero ",
"Hernan Alejandro Carrion ",
"Carlos Quinonez",
"Julio Salazar",
"Monica Altamirano",
"Ricardo Balzaretti",
"Daniel Espino",
"Yazmín Terán",
"Carlos A. Quiroz",
"Gabriel Pantoja",
"Vany Lopez",
"Francisco M",
"MARLON MAURICIO ARRIAZA PAZ",
"Gerber Bautista",
"Osaac Levy",
"Carolina Escobar de Fiallos",
"Guillermo Rivas",
"Emilio J. Kafie F.",
"Rene Sagastume",
"Noe Waldimar Portillo Lopez",
"Allan Salazar",
"Ana del Carmen Mazariegos Aparicio",
"Jeffrey L. Chitamul Roldan",
"Mario Schettini",
"Dianeth Rengifo",
"Laura Ferrua",
"Rogelio Sánchez",
"Cesar Melendez",
"Alex Guzman",
"Luis Felipe Trigueros ",
"Jean Pierre Quesada Castillo",
"Giuliano Feijoo",
"Manfred Aymeric",
"Narciso Lacayo Arguello",
"Marcelo Mantica",
"Yassir A. Meza Diaz",
"Hector Moreira De Trinidad",
"Gustavo Miranda Hernández",
"Moises Burgos",
"Rafael Bardales",
"Estuardo Mazariegos ",
"Cesar Abreu",
"Alfredo José Alcantara",
"Oscar R. Salgado",
"Rigoberto Funes ",
"Agustín de la Guardia",
"Javier Castillero ",
"Luis Carlos A.",
"Gerson Coto",
"Reynerio Edgardo Vasquez Becerra",
"Jose Garrido Alvarez  ",
"Ervin Alonso Garcia",
"Roys Johns Castillo Gutierrez",
"Gerardo Baltodano ",
"Alejandro Cifuentes Calderón",
"Arturo Sagrera Palomo",
"Elias Andaluz",
"Juan Pablo Galvez Villeda  ",
"Jose Fabricio Morataya ",
"Angel Salmeron",
"Rolando Carvajal",
"Rafael Segovia",
"Denys R. ",
"David Hernandez",
"Carlos E. Rodríguez",
"Enrique Payeras ",
"Milton P",
"Manuel Becerra Novelo ",
"Frank Dalton ",
"Luis Miguel Duarte Quevedo",
"Jaime Oyarzún Cruzat ",
"Alfonso Angel Palacio Mendoza ",
"Roberto Siem",
"Carlos René Samayoa Cajas",
"Javier Matias",
"Juan Duran",
"Hernan Muntaner ",
"Eyda E. Córdoba B.",
"Ricardo Ortega",
"Omar Montaldo",
"Marvin Pinto",
"Anzor Vladimir Martinez Aguilar",
"Virna Lessy Alvarenga de Flores",
"Allan Gerli",
"Daniel Carvajal Carvajal",
"Maria Andrea Arias",
"Andrey Acuña",
"Alex Gonzalez",
"Rafael Aguilar Villafranca",
"Francisco Ovidio Paz Canales ",
"Manuel Andrade",
"Pablo Andonie ",
"Tomas Sanchez",
"Edward Ramos",
"Maria Gabriela T. ",
"Julissa Yahosca Orozco Largaespada ",
"Marcela Sanchez",
"Roberto Federspiel ",
"Gabriel Eduardo Crespo Balderrama",
"Julio Barquero",
"Duniesky Diaz Olivera ",
"Kattia Rodriguez",
"Gustavo Esquivel",
"Sergio Venosa",
"Mario Alberto Muñoz Francés",
"Jorge Novoa",
"Alberto Calvo",
"Yeyny Santamaría",
"Karen Barahona",
"Jose Siman",
"Ingrid Rosa",
"Pamela Soto ",
"Marvin Gilberto Lucas Domínguez",
"Dieter Schulz ",
"Francisco Suriano",
"Juan Manuel Linares",
"Ricardo Martinelli Berrocal ",
"Mónica Jaén ",
"Liliana Caballero",
"María Teresa Umaña ",
"Patricia Carrasco Mato",
"Ericka Hernández Urbina ",
"Diego Alvarez",
"Freddy Vargas Solano",
"Darwin Siezar ",
"Maria Mercedes Lopez Reyes ",
"Walter Vega Monter",
"Jhonny Calderon Barahona ",
"Luis Gutierrez",
"Tomas F. Acuña",
"Oscar Méndez Reyes",
"Luis Fernando Céspedes Meléndez",
"Elvis Gomez",
"Abdiel Diaz ",
"Boris Diaz",
"Mario Deras",
"Juan Eduardo Interiano",
"Rene Alfaro",
"María José Reyes Bichara",
"Alción Carrasquilla Zurita",
"Franchesca Garcia ",
"Eric Sanchez",
"Oscar Herrera Mejia ",
"Asdrubal Vásquez ",
"Roy Elizondo",
"Linda Caligara",
"Gilberto Guzman",
"Jose Jaikel A.",
"Luis Carlos Esquivel ",
"Juan Solares ",
"Sergio Licardie",
"Josué Daniel Campos Salguero ",
"Mario Bastos Fonseca ",
"Erick Brenes",
"Javier Siman",
"Javier Bonilla",
"Antonio Pérez",
"Adriana Echandi ",
"Andrea Villalobos Núñez ",
"Yeiner Zuñiga ",
"Javier M. Fonseca ",
"Josephine maalouf ",
"Abisai Cortez",
"Julián Alvarado",
"Rodrigo Iglesias",
"Edgardo Hasbun ",
"Mayra Artiga",
"Joseph Pineda",
"Will Burke ",
"Carlos Carballo ",
"David Jesús Legaria Islas ",
"Victor Serrato París",
"Francisco Moncada",
"Edgar Escalante",
"Carlos F. Cruz",
"Juan José Penabad y Figueredo",
"Samir Lamrini",
"Elman Jovel Saravia Martinez",
"Jose Herrera Ramirez",
"Carlos Guzman",
"Antonio Archila",
"Alberto Fallas Arce",
"Dilana Campos Cruz",
"David E. Goff S.",
"Humberto Galo Beteta",
"Graciani Arias Gonzalez",
"José Luis Núñez",
"Daniella Facusse",
"Hector Onil Ramirez Carrasco",
"Douglas Cabuz",
"Kimberly Dominguez",
"Oscar Veroy",
"Jimmy Alvarado",
"Gustavo Barahona",
"Esteban Pacheco Quirós",
"Ronald Mauricio Pavón Aguilar",
"Marianela Malespin Palacios",
"Lesther David Silva Hernandez",
"Walter Arevalo",
"Nissán Enrique Cutzal Lara",
"CARLOS GERARDO MARCANO VELASQUEZ",
"Zahra David",
"Nahun Castillo",
"Francisco Antonio Castillo Sermeño",
"Karen Alejandra Reyes Leiva",
"Juan Carlos Pérez",
"Juan Carlos Mérida Herrarte",
"Michael Vonesh",
"Ferdinan Fernandez",
"Carlos Calderón",
"Andrea Vivas",
"Emilio Quiñonez Larach",
"Pablo Alejandro Godinez Escobar",
"Victor Manuel Wong",
"Victor Giron",
"Erick Estuardo García",
"Karla Del Valle Gudiel",
"Crystian Romero",
]

print("Nombres")
for name in Nombres:
    names = name.strip().split(" ")
    if len(names) > 2:
        print(names[0] + " " + names[1])
    else:
        print(names[0])

print("------------------")
print("Apellidos")
for lastname in Nombres:
    lastnames = lastname.strip().split(" ")
    if len(lastnames) > 2:
        print(lastnames[2])
    else:
        print(lastnames[1])


